export const skills: string[] = [
  "Proje Yönetimi",
  "Program Yönetimi",
  "PMO",
  "Dijital Dönüşüm",
  "Sağlık Bilişimi",
  "Kritik Altyapılar",
  "ICT Operasyonları",
  "Veri Merkezi",
  "Network",
  "Network Güvenliği",
  "Sanallaştırma",
  "Bulut Teknolojileri",
  "İş Sürekliliği",
  "Disaster Recovery",
  "IT Service Management",
  "Vendor Management",
  "Risk Yönetimi",
  "Agile",
  "Scrum",
  "PMP®",
];
